connection: &connection
 adapter: postgresql
 encoding: unicode
 host:     localhost
 pool: 5
 username: ENV["APP_DATABASE_USER"]
 password: ENV["APP_DATABASE_PASSWORD"]

development:
 <<: *connection
 database: workshops_development

test: &test
 <<: *connection
 database: travis_ci_test

production: &production
 <<: *connection
 database: workshops_production

