connection: &connection
 adapter: postgresql
 encoding: unicode
 host:     localhost
 pool: 5
 username: <%= ENV['RAILS_PG_USERNAME'] || Rails.application.credentials.dig(:postgres, :username) %>
 password: <%= ENV['RAILS_PG_PASS'] || Rails.application.credentials.dig(:postgres, :password) %>


development:
 <<: *connection
 database: workshops_development

test: &test
 <<: *connection
 database: travis_ci_test

production: &production
 <<: *connection
 database: workshops_production

